---
title: "R- TIDYVERSE, GGPLOT2, R CLINICAL PRORAMMIMG (PFS & ECG Shift table)"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">

This project is structured to help you build essential R skills while working with real-world  data.

# **Clinical R Programming**

Before diving into Clinical Reporting in R, we first provide solutions to basic and advanced data manipulation exercises, along with ggplot2 graphs and interactive 
plots. Try to solve the exercises yourself first! Practice ! Click the button 
<tt>Show</tt> for the solution.

In the second part, we define our own functions. If you find yourself copying and pasting code to make edits, pause and consider creating a function instead.

The third project involves creating a Shift Table. With both basic and advanced data manipulation techniques, this should be easy to follow. While familiarity with custom function creation is encouraged, it is not required.

The fourth project is a Progression Free Survival (PFS) table. Here, a high-level
understanding of Survival analysis is a requirement!

## Projects covered

1. Data Manipulation & Visualization
- Tidyverse & dplyr for efficient data wrangling
- Graphs and plots with ggplot2 
- Interactive plots

2. User-Defined Custom function
- Re-usability and clean code!
- Better than copy and paste!

3. ECG Shift Table

3. PFS Table







